### ISSUE TITLE
Segment fault at minisat/mtl/Vec.h:187

### ISSUE THREAD

**Issue by rainoftime** [usi-verification-and-security/opensmt#125]
Hi, for the following formula
[187.txt](https://github.com/usi-verification-and-security/opensmt/files/4778448/187.txt)

opensmt 1a7b724 throws a segment fault
~~~~
ASAN:SIGSEGV
=================================================================
==8571==ERROR: AddressSanitizer: stack-overflow on address 0x7ffd70f8aff8 (pc 0x7fb0169699bd bp 0x7ffd70f8b860 sp 0x7ffd70f8b000 T0)
    #0 0x7fb0169699bc in realloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x989bc)
    #1 0x67f50b in vec<Map<SymRef, PTRef, SymRefHash, Equal<SymRef> >::Pair>::capacity(int) /home/opensmt/src/minisat/mtl/Vec.h:187
    #2 0x67edf8 in vec<Map<SymRef, PTRef, SymRefHash, Equal<SymRef> >::Pair>::push() /home/opensmt/src/minisat/mtl/Vec.h:79
    #3 0x67e51b in Map<SymRef, PTRef, SymRefHash, Equal<SymRef> >::_insert(SymRef const&, PTRef const&) /home/opensmt/src/minisat/mtl/Map.h:77
    #4 0x67daef in Map<SymRef, PTRef, SymRefHash, Equal<SymRef> >::insert(SymRef const&, PTRef const&) /home/opensmt/src/minisat/mtl/Map.h:138
    #5 0x67cc8b in PtStore::addToCtermMap(SymRef&, PTRef) /home/opensmt/src/pterms/PtStore.cc:142
    #6 0x611875 in Logic::insertTermHash(SymRef, vec<PTRef> const&) /home/opensmt/src/logics/Logic.cc:1229
    #7 0x610415 in Logic::mkFun(SymRef, vec<PTRef> const&) /home/opensmt/src/logics/Logic.cc:1094
    #8 0x6116c6 in Logic::insertTerm(SymRef, vec<PTRef>&, char**) /home/opensmt/src/logics/Logic.cc:1214
    #9 0x652169 in LALogic::insertTerm(SymRef, vec<PTRef>&, char**) /home/pensmt/src/logics/LALogic.cc:731
    #10 0x60b834 in Logic::resolveTerm(char const*, vec<PTRef>&, char**) /home/opensmt/src/logics/Logic.cc:680
    #11 0x55e0a0 in Interpret::parseTerm(ASTNode const&, vec<LetFrame>&) /home/opensmt/src/api/Interpret.cc:585
    #12 0x55e972 in Interpret::parseTerm(ASTNode const&, vec<LetFrame>&) /home/opensmt/src/api/Interpret.cc:650
    #13 0x55ec70 in Interpret::parseTerm(ASTNode const&, vec<LetFrame>&) /home/opensmt/src/api/Interpret.cc:670
~~~~

**Comment by blishko** [comment]
Hi Jack,

is this Debug mode or Release?
In Release mode I just get (error "assertion returns an unknown sort") which suggests the formula is ill-formed.
In Debug mode, I get a stack-overflow when parsing, which also seems to be your error here. This is a known issue for us, but currently we do not have plans to fix it, since we have not encountered the problem in Release mode yet and you can work around this by increasing the stack limit for the process (or try different encoding of your problem).

**Comment by rainoftime** [comment]
It is in debug mode.
