### ISSUE TITLE
Segment fault at src/common/StringMap.h:41 on QF_UF formula

### ISSUE THREAD

**Issue by rainoftime** [usi-verification-and-security/opensmt#175]
Hi, for the following formula,
~~~~
(set-logic QF_UF)
(declare-sort I 0)
(declare-fun e0 () I)
(assert (= (as e0 I) (as e0 I)))
(check-sat)
~~~~

opensmt 6518bf9  throws a segfault,
but z3 can solve correctly
~~~~
ASAN:SIGSEGV
=================================================================
==147306==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x000000598a10 bp 0x7ffcfa858c80 sp 0x7ffcfa858c50 T0)
    #0 0x598a0f in StringHash::operator()(char const*) const /home/peisen/test/tofuzz/opensmt/src/common/StringMap.h:41
    #1 0x5db9b9 in std::__detail::_Hash_code_base<char const*, std::pair<char const* const, LetBinder>, std::__detail::_Select1st, StringHash, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, true>::_M_hash_code(char const* const&) const (/home/peisen/test/tofuzz/opensmt/build/opensmt+0x5db9b9)
    #2 0x5d1fec in std::_Hashtable<char const*, std::pair<char const* const, LetBinder>, std::allocator<std::pair<char const* const, LetBinder> >, std::__detail::_Select1st, Equal<char const*>, StringHash, std::__detail::_Mod_range_hashing, std::__detail::_Default_ranged_hash, std::__detail::_Prime_rehash_policy, std::__detail::_Hashtable_traits<true, false, true> >::find(char const* const&) const (/home/peisen/test/tofuzz/opensmt/build/opensmt+0x5d1fec)
    #3 0x5c589b in std::unordered_map<char const*, LetBinder, StringHash, Equal<char const*>, std::allocator<std::pair<char const* const, LetBinder> > >::find(char const* const&) const (/home/peisen/test/tofuzz/opensmt/build/opensmt+0x5c589b)
    #4 0x5bff18 in LetRecords::getOrUndef(char const*) const (/home/peisen/test/tofuzz/opensmt/build/opensmt+0x5bff18)
    #5 0x5a7085 in Interpret::letNameResolve(char const*, LetRecords const&) const /home/peisen/test/tofuzz/opensmt/src/bin/Interpret.cc:395
    #6 0x5a7b50 in Interpret::parseTerm(ASTNode const&, LetRecords&) /home/peisen/test/tofuzz/opensmt/src/bin/Interpret.cc:416
    #7 0x5a8183 in Interpret::parseTerm(ASTNode const&, LetRecords&) /home/peisen/test/tofuzz/opensmt/src/bin/Interpret.cc:436
    #8 0x5a51a9 in Interpret::interp(ASTNode&) /home/peisen/test/tofuzz/opensmt/src/bin/Interpret.cc:239
    #9 0x5b3371 in Interpret::execute(ASTNode const*) /home/peisen/test/tofuzz/opensmt/src/bin/Interpret.cc:947
    #10 0x5b3610 in Interpret::interpFile(_IO_FILE*) /home/peisen/test/tofuzz/opensmt/src/bin/Interpret.cc:960
    #11 0x597920 in main /home/peisen/test/tofuzz/opensmt/src/bin/opensmt.cc:147
    #12 0x7f42c0a7a83f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2083f)
    #13 0x596588 in _start (/home/peisen/test/tofuzz/opensmt/build/opensmt+0x596588)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /home/peisen/test/tofuzz/opensmt/src/common/StringMap.h:41 StringHash::operator()(char const*) const
==147306==ABORTING
~~~~

**Comment by blishko** [comment]
It seems OpenSMT does not support the `as` keyword yet.

The expected behaviour is described in section 3.6 of SMT-LIB v2.6.

**Comment by blishko** [comment]
I believe this is now fixed. Most likely in #426, or related PRs.
