### ISSUE TITLE
Memory leak on QF_UF formula

### ISSUE THREAD

**Issue by rainoftime** [usi-verification-and-security/opensmt#178]
Hi, for the formula below
opensmt 6518bf9 
~~~~
$ ./opensmt x.smt2 
unsat

=================================================================
==193116==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 2 byte(s) in 1 object(s) allocated from:
    #0 0x7f5e25651662 in malloc (/usr/lib/x86_64-linux-gnu/libasan.so.2+0x98662)
    #1 0x7f5e233567d7 in vasprintf (/lib/x86_64-linux-gnu/libc.so.6+0x767d7)

SUMMARY: AddressSanitizer: 2 byte(s) leaked in 1 allocation(s).
$ cat x.smt2 
(set-logic QF_UF)
(declare-sort U 0)
(declare-fun x () U)
(declare-fun y () U)
(assert (distinct x y))
(assert (let ((x y) (y x)) (= x y)))
(check-sat)
~~~~

**Comment by blishko** [comment]
Fixed by #339
