### ISSUE TITLE
ASAN memory leak at Theory.h:91

### ISSUE THREAD

**Issue by rainoftime** [usi-verification-and-security/opensmt#70]
Hi, for the following formula
~~~~
(set-logic QF_LRA)
(assert (not (>= 12008827.0 2805085.0)))
(check-sat)
~~~~

ASAN detects a memory leak in opensmt (commit e9e14b4)

~~~~
=================================================================
==39649==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 8 byte(s) in 1 object(s) allocated from:
    #0 0x7f5045f7df80 in realloc (/usr/lib/x86_64-linux-gnu/libasan.so.4+0xdef80)
    #1 0x4b7073 in vec<PTRef>::capacity(int) /home/rainoftime/Work/tofuzz/opensmt/src/minisat/mtl/Vec.h:180
    #2 0x4b40e6 in vec<PTRef>::push(PTRef const&) /home/rainoftime/Work/tofuzz/opensmt/src/minisat/mtl/Vec.h:80
    #3 0x4b0fa1 in PushFrame::push(PTRef) /home/rainoftime/Work/tofuzz/opensmt/src/logics/Theory.h:91
    #4 0x4b257c in MainSolver::MainSolver(THandler&, SMTConfig&, SimpSMTSolver*, char const*) (/home/rainoftime/Work/tofuzz/opensmt/build/src/b
in/opensmt+0x4b257c)
    #5 0x4a3898 in Interpret::interp(ASTNode&) /home/rainoftime/Work/tofuzz/opensmt/src/api/Interpret.cc:240
    #6 0x4ad480 in Interpret::execute(ASTNode const*) /home/rainoftime/Work/tofuzz/opensmt/src/api/Interpret.cc:1044
    #7 0x4ad680 in Interpret::interpFile(_IO_FILE*) /home/rainoftime/Work/tofuzz/opensmt/src/api/Interpret.cc:1057
    #8 0x49cf4a in main /home/rainoftime/Work/tofuzz/opensmt/src/bin/opensmt.cc:129
    #9 0x7f504490882f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
~~~~

**Comment by blishko** [comment]
There seems to be a memory leak, because the destructor for PushFrame is never called.
It's because the PushFrameAllocator, which inherits from RegionAllocator, does not call destructor on its allocated elements. In most case these allocators allocated simple objects, but PushFrame seems to be an exception.

@aehyvari , is there a way to call destructor on elements allocated by the PushFrameAllocator?
