### ISSUE TITLE
Segment fault at CoreSMTSolver.cc:1425

### ISSUE THREAD

**Issue by rainoftime** [usi-verification-and-security/opensmt#74]
Hi, for the following formula,
~~~~
(set-logic QF_LRA)
(push 1)
(check-sat)
(pop 1)
(push 1)
(check-sat)
(pop 1)
(check-sat)
(assert false)
(check-sat)
(check-sat)
(push 1)
(check-sat)
(push 1)
(push 1)
(check-sat)
(check-sat)
(pop 1)
(assert true)
(check-sat)
(push 1)
(check-sat)
(push 1)
(check-sat)
(assert true)
(check-sat)
(assert true)
(check-sat)
(push 1)
(check-sat)
(push 1)
(check-sat)
(assert true)
(check-sat)
(check-sat)
~~~~
ASAN detects a SEGV in opensmt (commit 04c7fa341d)
~~~~
ASAN:DEADLYSIGNAL
=================================================================
==12659==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000000 (pc 0x0000004fc0ca bp 0x7ffd9b36cf00 sp 0x7ffd9b36cae0 T0)
==12659==The signal is caused by a READ memory access.
==12659==Hint: address points to the zero page.
    #0 0x4fc0c9 in CoreSMTSolver::propagate() /home/rainoftime/Work/tofuzz/opensmt/src/smtsolvers/CoreSMTSolver.cc:1425
    #1 0x5001c0 in CoreSMTSolver::search(int, int) /home/rainoftime/Work/tofuzz/opensmt/src/smtsolvers/CoreSMTSolver.cc:1892
    #2 0x5043d2 in CoreSMTSolver::solve_() /home/rainoftime/Work/tofuzz/opensmt/src/smtsolvers/CoreSMTSolver.cc:2306
    #3 0x4ddcde in SimpSMTSolver::solve_(bool, bool) /home/rainoftime/Work/tofuzz/opensmt/src/smtsolvers/SimpSMTSolver.cc:165
    #4 0x643eaf in SimpSMTSolver::solve(vec<Lit> const&, bool, bool) /home/rainoftime/Work/tofuzz/opensmt/src/smtsolvers/SimpSMTSolver.h:202
    #5 0x63f206 in Cnfizer::solve(vec<FrameId>&) /home/rainoftime/Work/tofuzz/opensmt/src/cnfizers/Cnfizer.cc:88
    #6 0x4bf766 in MainSolver::solve() /home/rainoftime/Work/tofuzz/opensmt/src/api/MainSolver.cc:389
    #7 0x4bf423 in MainSolver::check() /home/rainoftime/Work/tofuzz/opensmt/src/api/MainSolver.cc:375
    #8 0x4a910f in Interpret::checkSat() /home/rainoftime/Work/tofuzz/opensmt/src/api/Interpret.cc:697
    #9 0x4a5b7d in Interpret::interp(ASTNode&) /home/rainoftime/Work/tofuzz/opensmt/src/api/Interpret.cc:415
    #10 0x4ae160 in Interpret::execute(ASTNode const*) /home/rainoftime/Work/tofuzz/opensmt/src/api/Interpret.cc:1044
    #11 0x4ae360 in Interpret::interpFile(_IO_FILE*) /home/rainoftime/Work/tofuzz/opensmt/src/api/Interpret.cc:1057
    #12 0x49dc2a in main /home/rainoftime/Work/tofuzz/opensmt/src/bin/opensmt.cc:129
    #13 0x7fa53677082f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
    #14 0x49d0d8 in _start (/home/rainoftime/Work/tofuzz/opensmt/build/src/bin/opensmt+0x49d0d8)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /home/rainoftime/Work/tofuzz/opensmt/src/smtsolvers/CoreSMTSolver.cc:1425 in CoreSMTSolver::propagate()
~~~~

**Comment by blishko** [comment]
Fixed by #91
