### ISSUE TITLE
heap-buffer-over-flow at src/minisat/core/SolverTypes.h:112

### ISSUE THREAD

**Issue by rainoftime** [usi-verification-and-security/opensmt#75]
Hi, for the following formula,
~~~~
(set-logic QF_LRA)
(declare-fun r2 () Real)
(declare-fun v7 () Bool)
(declare-fun v19 () Bool)
(assert (xor v7 v19))
(assert (< r2 0.0))
(assert (distinct true (not (<= 0.0 r2))))
(push 1)
(check-sat)
(check-sat)
(push 1)
(check-sat)
(check-sat)
(check-sat)
(pop 1)
(push 1)
(check-sat)
~~~~

ASAN detects an overflow in opensmt (commit 04c7fa3)
~~~~
==32108==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x602000004538 at pc 0x0000004c97a2 bp 0x7ffeb6c5aef0 sp 0x7ffeb6c5aee0
READ of size 1 at 0x602000004538 thread T0
    #0 0x4c97a1 in lbool::operator^(bool) const /home/rainoftime/Work/tofuzz/opensmt/src/minisat/core/SolverTypes.h:112
    #1 0x4ca664 in CoreSMTSolver::value(Lit) const /home/rainoftime/Work/tofuzz/opensmt/src/smtsolvers/CoreSMTSolver.h:1013
    #2 0x500e74 in CoreSMTSolver::search(int, int) /home/rainoftime/Work/tofuzz/opensmt/src/smtsolvers/CoreSMTSolver.cc:2005
    #3 0x5043d2 in CoreSMTSolver::solve_() /home/rainoftime/Work/tofuzz/opensmt/src/smtsolvers/CoreSMTSolver.cc:2306
    #4 0x4ddcde in SimpSMTSolver::solve_(bool, bool) /home/rainoftime/Work/tofuzz/opensmt/src/smtsolvers/SimpSMTSolver.cc:165
    #5 0x643eaf in SimpSMTSolver::solve(vec<Lit> const&, bool, bool) /home/rainoftime/Work/tofuzz/opensmt/src/smtsolvers/SimpSMTSolver.h:202
    #6 0x63f206 in Cnfizer::solve(vec<FrameId>&) /home/rainoftime/Work/tofuzz/opensmt/src/cnfizers/Cnfizer.cc:88
    #7 0x4bf766 in MainSolver::solve() /home/rainoftime/Work/tofuzz/opensmt/src/api/MainSolver.cc:389
    #8 0x4bf423 in MainSolver::check() /home/rainoftime/Work/tofuzz/opensmt/src/api/MainSolver.cc:375
    #9 0x4a910f in Interpret::checkSat() /home/rainoftime/Work/tofuzz/opensmt/src/api/Interpret.cc:697
    #10 0x4a5b7d in Interpret::interp(ASTNode&) /home/rainoftime/Work/tofuzz/opensmt/src/api/Interpret.cc:415
    #11 0x4ae160 in Interpret::execute(ASTNode const*) /home/rainoftime/Work/tofuzz/opensmt/src/api/Interpret.cc:1044
    #12 0x4ae360 in Interpret::interpFile(_IO_FILE*) /home/rainoftime/Work/tofuzz/opensmt/src/api/Interpret.cc:1057
    #13 0x49dc2a in main /home/rainoftime/Work/tofuzz/opensmt/src/bin/opensmt.cc:129
    #14 0x7f6d0181082f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
    #15 0x49d0d8 in _start (/home/rainoftime/Work/tofuzz/opensmt/build/src/bin/opensmt+0x49d0d8)
~~~~

**Comment by blishko** [comment]
Fixed by #91
