### ISSUE TITLE
heap-buffer-over-flow at src/minisat/mtl/Vec.h:64

### ISSUE THREAD

**Issue by rainoftime** [usi-verification-and-security/opensmt#76]
Hi, for the following formula,
~~~~
(set-logic QF_LRA)
(declare-fun v1 () Bool)
(declare-fun v4 () Bool)
(declare-fun v5 () Bool)
(assert v4)
(check-sat)
(assert v1)
(check-sat)
(declare-fun r12 () Real)
(assert (not v5))
(assert v5)
(check-sat)
(push 1)
(check-sat)
(pop 1)
(assert true)
(check-sat)
(push 1)
(assert (= 0.0 r12))
(check-sat)
(pop 1)
(assert true)
(check-sat)
(check-sat)
(push 1)
(check-sat)
(check-sat)
(check-sat)
(check-sat)
(check-sat)
(check-sat)
(check-sat)
(pop 1)
(check-sat)
~~~~

ASAN detects an overflow in opensmt (commit 04c7fa3)
~~~~
=================================================================
==42255==ERROR: AddressSanitizer: heap-buffer-overflow on address 0x6110000009e0 at pc 0x00000050c7b7 bp 0x7fff8d4ac4c0 sp 0x7fff8d4ac4b0
READ of size 8 at 0x6110000009e0 thread T0
    #0 0x50c7b6 in vec<CoreSMTSolver::Watcher>::operator CoreSMTSolver::Watcher*() /home/rainoftime/Work/tofuzz/opensmt/src/minisat/mtl/Vec.h:6
4
    #1 0x4fc017 in CoreSMTSolver::propagate() /home/rainoftime/Work/tofuzz/opensmt/src/smtsolvers/CoreSMTSolver.cc:1422
    #2 0x5001c0 in CoreSMTSolver::search(int, int) /home/rainoftime/Work/tofuzz/opensmt/src/smtsolvers/CoreSMTSolver.cc:1892
    #3 0x5043d2 in CoreSMTSolver::solve_() /home/rainoftime/Work/tofuzz/opensmt/src/smtsolvers/CoreSMTSolver.cc:2306
    #4 0x4ddcde in SimpSMTSolver::solve_(bool, bool) /home/rainoftime/Work/tofuzz/opensmt/src/smtsolvers/SimpSMTSolver.cc:165
    #5 0x643eaf in SimpSMTSolver::solve(vec<Lit> const&, bool, bool) /home/rainoftime/Work/tofuzz/opensmt/src/smtsolvers/SimpSMTSolver.h:202
    #6 0x63f206 in Cnfizer::solve(vec<FrameId>&) /home/rainoftime/Work/tofuzz/opensmt/src/cnfizers/Cnfizer.cc:88
    #7 0x4bf766 in MainSolver::solve() /home/rainoftime/Work/tofuzz/opensmt/src/api/MainSolver.cc:389
    #8 0x4bf423 in MainSolver::check() /home/rainoftime/Work/tofuzz/opensmt/src/api/MainSolver.cc:375
    #9 0x4a910f in Interpret::checkSat() /home/rainoftime/Work/tofuzz/opensmt/src/api/Interpret.cc:697
    #10 0x4a5b7d in Interpret::interp(ASTNode&) /home/rainoftime/Work/tofuzz/opensmt/src/api/Interpret.cc:415
    #11 0x4ae160 in Interpret::execute(ASTNode const*) /home/rainoftime/Work/tofuzz/opensmt/src/api/Interpret.cc:1044
    #12 0x4ae360 in Interpret::interpFile(_IO_FILE*) /home/rainoftime/Work/tofuzz/opensmt/src/api/Interpret.cc:1057
    #13 0x49dc2a in main /home/rainoftime/Work/tofuzz/opensmt/src/bin/opensmt.cc:129
    #14 0x7fc572cf682f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
    #15 0x49d0d8 in _start (/home/rainoftime/Work/tofuzz/opensmt/build/src/bin/opensmt+0x49d0d8)
~~~~

**Comment by blishko** [comment]
Fixed by #91
