### ISSUE TITLE
Segment fault for QF_RDL instance at src/minisat/mtl/Vec.h:67

### ISSUE THREAD

**Issue by rainoftime** [usi-verification-and-security/opensmt#93]
Hi, for the following formula,
~~~~
(set-logic QF_RDL)
(push 1)
(check-sat)
~~~~

opensmt (commit a492c6168) throws a seg fault
~~~~
(error "unknown logic QF_RDL")

ASAN:DEADLYSIGNAL
=================================================================
==2022==ERROR: AddressSanitizer: SEGV on unknown address 0x000000000090 (pc 0x0000004b9175 bp 0x7ffd22f29a70 sp 0x7ffd22f29a60 T0)
==2022==The signal is caused by a READ memory access.
==2022==Hint: address points to the zero page.
    #0 0x4b9174 in vec<PFRef>::size() const /home/rainoftime/Work/tofuzz/opensmt/src/minisat/mtl/Vec.h:67
    #1 0x4b61a5 in MainSolver::PushFramesWrapper::last() const /home/rainoftime/Work/tofuzz/opensmt/src/api/MainSolver.h:73
    #2 0x4c75cd in MainSolver::getLastFrame() const /home/rainoftime/Work/tofuzz/opensmt/src/api/MainSolver.h:137
    #3 0x4c7621 in MainSolver::isLastFrameUnsat() const /home/rainoftime/Work/tofuzz/opensmt/src/api/MainSolver.h:138
    #4 0x4c057a in MainSolver::push() /home/rainoftime/Work/tofuzz/opensmt/src/api/MainSolver.cc:44
    #5 0x4ac3d2 in Interpret::push() /home/rainoftime/Work/tofuzz/opensmt/src/api/Interpret.cc:729
    #6 0x4a908c in Interpret::interp(ASTNode&) /home/rainoftime/Work/tofuzz/opensmt/src/api/Interpret.cc:466
    #7 0x4b10d8 in Interpret::execute(ASTNode const*) /home/rainoftime/Work/tofuzz/opensmt/src/api/Interpret.cc:1044
    #8 0x4b12d8 in Interpret::interpFile(_IO_FILE*) /home/rainoftime/Work/tofuzz/opensmt/src/api/Interpret.cc:1057
    #9 0x4a0b1a in main /home/rainoftime/Work/tofuzz/opensmt/src/bin/opensmt.cc:129
    #10 0x7f7ceed0c82f in __libc_start_main (/lib/x86_64-linux-gnu/libc.so.6+0x2082f)
    #11 0x49ffc8 in _start (/home/rainoftime/Work/tofuzz/opensmt/build/src/bin/opensmt+0x49ffc8)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV /home/rainoftime/Work/tofuzz/opensmt/src/minisat/mtl/Vec.h:67 in vec<PFRef>::size() const
~~~~

Why does opensmt issue a warning "(error "unknown logic QF_RDL")"?
In the README, it says that QF_UF, QF_RDL, QF_LIA, and QF_LRA are supported.

**Comment by blishko** [comment]
fixed in PR #98, commit b12e5a2254656bf5fa28acc84f32ff19cd484b74

**Comment by rainoftime** [comment]
Perhaps the solver can terminate directly when encountering an unknown logic?
When setting some other logic like UFNRA, asan can still report the above issue.

**Comment by blishko** [comment]
That's a good point. We will see what we can do about it.
